# Simple Pod with single container
apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    app: web-server
    version: v1.0
  annotations:
    description: "Simple nginx web server"
    created-by: "learning-tutorial"
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
      name: http
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
