# Pod using ConfigMaps and Secrets as environment variables
apiVersion: v1
kind: Pod
metadata:
  name: env-vars-example
  labels:
    app: config-demo
spec:
  containers:
  - name: app-container
    image: busybox:1.35
    command: ["/bin/sh"]
    args:
      - -c
      - |
        echo "=== Environment Variables ==="
        echo "Database Host: $DB_HOST"
        echo "Database Port: $DB_PORT"
        echo "Database Name: $DB_NAME"
        echo "Log Level: $LOG_LEVEL"
        echo "Environment: $ENVIRONMENT"
        echo "Debug Mode: $DEBUG_MODE"
        echo "Database User: $DB_USER"
        echo "API Key: $API_KEY (hidden for security)"
        echo ""
        echo "=== Application Configuration ==="
        echo "Starting application with above configuration..."
        while true; do
          echo "$(date): Application running with $ENVIRONMENT configuration"
          sleep 30
        done
    
    env:
    # Environment variables from ConfigMap (individual keys)
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: database.host
    - name: DB_PORT
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: database.port
    - name: DB_NAME
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: database.name
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: log.level
    
    # Environment variables from Secret (individual keys)
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: database-secret
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: database-secret
          key: password
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: api-secrets
          key: api-key
    
    # Direct environment variables
    - name: ENVIRONMENT
      value: "development"
    - name: DEBUG_MODE
      value: "true"
    
    # Environment variables from pod metadata
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    
    # Environment variables from resource limits
    - name: MEMORY_LIMIT
      valueFrom:
        resourceFieldRef:
          containerName: app-container
          resource: limits.memory
    - name: CPU_LIMIT
      valueFrom:
        resourceFieldRef:
          containerName: app-container
          resource: limits.cpu
    
    # Load all keys from ConfigMap as environment variables
    envFrom:
    - configMapRef:
        name: dev-config
    - secretRef:
        name: app-secrets
    
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
---
# Deployment using environment variables from multiple sources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-with-env
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: nginx:1.21
        ports:
        - containerPort: 80
        
        env:
        # Application configuration
        - name: APP_ENV
          value: "production"
        - name: APP_VERSION
          value: "v2.1.0"
        
        # Database configuration from ConfigMap and Secret
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: database.host
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: password
        
        # Pod and node information
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        
        # Load all environment-specific configuration
        envFrom:
        - configMapRef:
            name: prod-config
        - secretRef:
            name: api-secrets
        
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
