# Namespace and RBAC Configuration for Production E-commerce Platform

apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce-prod
  labels:
    name: ecommerce-prod
    environment: production
    team: platform-engineering
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: "environment=production"

---
apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce-monitoring
  labels:
    name: ecommerce-monitoring
    environment: production
    team: platform-engineering

---
# Resource Quota for production namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ecommerce-prod-quota
  namespace: ecommerce-prod
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "20"
    services: "30"
    secrets: "20"
    configmaps: "20"
    count/deployments.apps: "15"
    count/statefulsets.apps: "10"
    count/jobs.batch: "5"

---
# Limit Range for pod resource constraints
apiVersion: v1
kind: LimitRange
metadata:
  name: ecommerce-prod-limits
  namespace: ecommerce-prod
spec:
  limits:
  - default:
      memory: "1Gi"
      cpu: "500m"
    defaultRequest:
      memory: "256Mi"
      cpu: "100m"
    type: Container
  - max:
      memory: "4Gi"
      cpu: "2"
    min:
      memory: "128Mi"
      cpu: "50m"
    type: Container
