# Service to expose the advanced web application
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  labels:
    app: web-app
spec:
  selector:
    app: web-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: metrics
    port: 9100
    targetPort: 9100
    protocol: TCP
  type: ClusterIP

---
# Service for external access (LoadBalancer for GKE)
apiVersion: v1
kind: Service
metadata:
  name: web-app-external
  labels:
    app: web-app
  annotations:
    # GKE-specific annotations
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "web-app-backend-config"}'
spec:
  selector:
    app: web-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer  # This will create a GCP Load Balancer
